# Generated by Django 5.2.8 on 2025-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
